name: Full CI CD Pipeline

on:
  push:
    branches:
      - 'feature/**'
  workflow_dispatch:

env:
  APP_NAME: evershop

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:

  secret-scan:
    name: Secret Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gitleaks/gitleaks-action@v2


  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: secret-scan

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci
      - run: npm run compile
      - run: npm run compile:db

      - name: Save workspace
        uses: actions/upload-artifact@v4
        with:
          name: workspace
          path: |
            .
            node_modules
            packages/**/dist


  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: workspace

      - run: npm install --prefer-offline --no-audit
      - run: npm run lint --if-present


  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: workspace

      - run: npm install --prefer-offline --no-audit
      - run: npm test -- --passWithNoTests


docker:
  name: Build & Push Docker Image
  runs-on: ubuntu-latest
  needs: test

  steps:
    - name: Download workspace
      uses: actions/download-artifact@v4
      with:
        name: workspace
        path: workspace

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      working-directory: workspace
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/evershop:${{ github.sha }} .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/evershop:${{ github.sha }}




  deploy:
    name: Deploy Container
    runs-on: ubuntu-latest
    needs: docker
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Pull image
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/evershop:${{ github.sha }}

      - name: Run container
        run: |
          docker run -d -p 3000:3000 \
          --name evershop-${{ github.run_number }} \
          ${{ secrets.DOCKER_USERNAME }}/evershop:${{ github.sha }}
